### ISSUE TITLE
VADR Annotation

### ISSUE THREAD

**Issue by fanninpm** [CFIA-NCFAD/nf-flu#62]
### Problem description

Version 1.6.3 of [VADR](https://github.com/ncbi/vadr) was released recently, adding support for [influenza annotation](https://github.com/ncbi/vadr/wiki/Influenza-annotation) (similar to [FLAN](https://doi.org/10.1093/nar/gkm354)). You might be interested in using VADR to annotate the consensus sequences generated from this workflow.

**Comment by peterk87** [comment]
Thanks @fanninpm for letting me know about VADR now supporting Influenza genome annotation. 

It looks like the Bioconda package hasn't been updated in a while and v1.5.1 is the latest. I'll see if I can get it updated based on the changes in https://github.com/bioconda/bioconda-recipes/pull/44370

**Comment by Codes1985** [comment]
Just to follow up on this, I pulled the VADR singularity image from [staphb](https://hub.docker.com/r/staphb/vadr/tags), and running it as a post-processing step after nf-flu finishes.  So far it has been working well, and we are using it as part of our QC regime prior to uploading our data to GISAID.

**Comment by peterk87** [comment]
@Codes1985 that's great to know! I wonder if staphb have a Conda channel since I don't seem to be getting anywhere with trying to [update VADR in Bioconda](https://github.com/bioconda/bioconda-recipes/pull/45235). Bioconda MacOSX builds are the bane of my existence... I usually skip them for my own tools. I wonder if I can get away with adding an OSX skip in my PR.

**Comment by peterk87** [comment]
VADR annotation has been added in #73 and version [3.4.0](https://github.com/CFIA-NCFAD/nf-flu/releases/tag/3.4.0). Hopefully that helps with your downstream needs @fanninpm!
